version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  # api: 
  #   build: ./API
  #   depends_on: 
  #     - mongodb
  #   container_name: api
  #   ports:
  #     - "5000:5000"
  keycloak:
    depends_on: 
      - mongodb
      # - api
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    volumes:
      - ./keycloak/:/opt/keycloak/data
    ports:
      - 8080:8080

  